### ISSUE TITLE
Bug with payload CMS using version 1.17.0

### ISSUE THREAD

**Issue by alexdieudonne** [upload-io/upload-javascript-sdk#2]
Hello, I'm a developper and a client of UPLOAD, your system is very full you did a great job with this sdk too thank you a lot. But my problem is the following. 
I'm trying to build an app using a framework [Payload CMS](https://github.com/payloadcms/payload)
but when i try to implement your sdk since the version 1.17.0 the framework crash.

<img width="1057" height="512" alt="Screenshot 2023-01-31 at 23 41 39" src="https://user-images.githubusercontent.com/59718717/215900361-69a87163-76c2-4d39-a07b-c7c0d9511c6d.png">

I don't have any logs to help me, but when i install the previous version (1.16.0) every goes well

<img width="1052" height="512" alt="Screenshot 2023-01-31 at 23 41 13" src="https://user-images.githubusercontent.com/59718717/215900300-d1a840ed-de41-403e-b76b-77ce6a6f0c6d.png">

So i was wondering about the fact that you put a `module:true` inside the webpack config.

[https://github.com/upload-io/upload-javascript-sdk/compare/v1.16.0...v1.17.0](url)

<img width="1520" alt="Screenshot 2023-01-31 at 23 30 55" src="https://user-images.githubusercontent.com/59718717/215898909-4a0b3639-9481-44db-ac5f-7fc8596682b8.png">

**Or maybe you could help me find out what's wrong, thank you.**

**Comment by ljwagerfield** [comment]
Hi @alexdieudonne!

Please can you share the following:

- NPM Version (`npm --version`)
- Node Version (`node --version`)
- Which build tool you're using (e.g. WebPack v5)

Many thanks!
Lawrence

**Comment by alexdieudonne** [comment]
Hello, @ljwagerfield 
These are my configurations
`npm version : 8.19.1`
`node version : 8.19.1`
`node  webpack@5.74.0`


And yes the error occur with the version 1.20.0

---
**Thanks for your help, but i'll use Imagekit it offers me more possibilities with less price than upload io, Thanks again for everything.**

**Comment by ljwagerfield** [comment]
Hi @alexdieudonne!

Thank you for the feedback 😊 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/3638917/216165878-63f88b17-5809-4e4c-ae6d-2ebf79923c06.png">

Are you sure you're using Node 8.19.1? 

Did you mean `Node.js 18.9.1` instead?

**Comment by alexdieudonne** [comment]
oh yes it's v18.9.0

**Comment by ljwagerfield** [comment]
Fixed in `1.22.0`
